server: 
  port: 9002
spring: 
  application: 
    name: hrm-course
  datasource: 
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/hrm_course
      username: root
      password: 12345678
mybatis-plus: 
  mapper-locations: classpath:com/sunwei/hrm/mapper/*Mapper.xml
  type-aliases-package: com.sunwei.hrm.domain,com.sunwei.hrm.query